### ISSUE TITLE
Dashboard - Online Shop DEG Süd 

### ISSUE THREAD

**Issue by Leapauen** [convidera/zedach-icon-font#2]
![image.png](https://images.zenhubusercontent.com/5d14765856314a36269e1a5b/20d1db14-41df-4271-831a-10780996620f)

DE Süd members have a different online shop than OBIS.
-> When chosen DE Süd in the registration process, we need to show their logo and link it to their online shop: https://www.deg-sued.de/dde/de/

**Comment by Leapauen** [comment]
@tjansn

**Comment by tjansn** [comment]
- is already implemented and live 
- wrong repository
